# Generated by Django 5.2.5 on 2025-10-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_submission_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='comments',
            new_name='comment',
        ),
    ]
