# Generated by Django 5.2.5 on 2025-09-16 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectContributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
