name: Deploy Django to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '#deploy') || contains(github.event.head_commit.message, '#backend')
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/GitCollab.io
            git fetch origin
            git reset --hard origin/main
            cd server
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gitcollab
            sudo systemctl restart nginx
